# Generated by Django 4.2.5 on 2023-09-21 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_rename_first_name_customuser_full_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
