# Generated by Django 4.2.5 on 2023-09-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0014_course_follow_course_lesson_number_course_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(max_length=300)),
                ('order', models.SmallIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='course',
            old_name='user',
            new_name='Teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='type_id',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
