# Generated by Django 4.2.5 on 2023-09-27 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0016_alter_coursecategories_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userApp.coursecategories'),
            preserve_default=False,
        ),
    ]
